name: Node.js CI

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install CI
      run: npm ci
    - name: Install other dependecies
      run: npm install
    - name: Run tests
      run: npm test
      continue-on-error: true
    - name: Run tests with coverage
      run: npm run coverage
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2.3.4
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        path-to-lcov: "../.nyc_output"
        debug: true